---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-Deployment
  namespace: prod
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: subhankarpaul/backend-nodejsproject:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysq-svc"  # Use the service name and database name
        - name: DB_USER
          value: "root"  # MySQL root user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-databse-name-config
              key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
